version: '2'
services:
  db:
    image: culturagovbr/db-postgresql-debian
    volumes:
    - /var/www/db/postgresql/data:/var/www/project/db/data
    ports:
    - 5432:5432
    expose:
    - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data
    labels:
      com.salic.description: "Banco de dados Postgres"
  web:
    image: culturagovbr/web-apache-php5-debian
    volumes:
    - /var/www:/var/www
    ports:
    - 80:80
    expose:
    - 80
    links:
    - db
    extra_hosts:
    - "localhost:127.0.0.1"
    - "local.salic:127.0.0.1"
    command: "/bin/bash apachectl -D FOREGROUND"
    restart: always
    labels:
      com.salic.description: "Aplicação web"